### ISSUE TITLE
Please Update README.md

### ISSUE THREAD

**Issue by miss85246** [lixxu/sanic-motor#10]
Hi there, I use sanic-motor today, I think this is a great project, but your document is too simple and outdated, which makes me confused.

some functions such as  `find()` and `find_one()`  are  different than your example usage,  I found  these can't find any document by your example way. I need add `as_raw`   and some other params can get the result, like this:
```python
document = await Test.find_one({"id": "tw1296781020646313999"}, {"_id": 0}, as_raw=True)
document = await Test.find(request, {"id": "tw1296781020646313999"}, {"_id": 0}, as_raw=True)
```

This is really a waste of time, can you update your `README.md` or update your examples in your free time ?  
Looking forward to your reply, thank you very much!

**Comment by lixxu** [comment]
`as_raw` is only the option to convert the records to model class instances or keep dict format.
`find_one` will return the found record or `None`, and `find` will return a cursor.
So, should be like this:

```
cur = await Test.find(request, {"id": "tw1296781020646313999"}, {"_id": 0}, as_raw=True)
docs = cur.objects
```
