### ISSUE TITLE
warning when  sanic run in mulit workers

### ISSUE THREAD

**Issue by gxy501** [lixxu/sanic-motor#12]
UserWarning: MongoClient opened before fork. Create MongoClient only after forking. See PyMongo's documentation for details: https://pymongo.readthedocs.io/en/stable/faq.html#is-pymongo-fork-safe

**Comment by lixxu** [comment]
try new version `0.6.0` and pass `connect=False` to `init_app` method.

**Comment by gxy501** [comment]
thanks
