### ISSUE TITLE
关于find

### ISSUE THREAD

**Issue by topmy** [lixxu/sanic-motor#7]
大神，何时有时间可以提供下find详细点API说明，复杂点查询都搞晕了

**Comment by lixxu** [comment]
基本上就是按照[https://motor.readthedocs.io/en/stable/api-asyncio/asyncio_motor_collection.html#motor.motor_asyncio.AsyncIOMotorCollection.find](https://motor.readthedocs.io/en/stable/api-asyncio/asyncio_motor_collection.html#motor.motor_asyncio.AsyncIOMotorCollection.find) 的参数来的, 另外加了一些分页的参数在里面, 还有时区的参数, 其他的都是 `motor` 的标准参数了, 看它的文档就行了.

**Comment by topmy** [comment]
@lixxu 
好的，谢谢啦！
