### ISSUE TITLE
find() is not returning results

### ISSUE THREAD

**Issue by pwalimbe** [lixxu/sanic-motor#9]
@bp_v1.route("/companies", methods=["GET"])
async def handle(request):
    query = {}
    cur = await Company.find(filter=query)
    results = cur.objects
    return json({"Status": "Success", "companies": results})

The above query is giving error that coroutine is not callable or NoneType is not callable. I tried all variations of filter or even to_list but not working. The below query worked fine though.

@bp_v1.route("/companies/add", methods=["POST"])
async def handle(request):
    if request.method == 'POST':
        company = request.json
        res = await Company.insert_one(company)
        if res:
            return json({"Status": "Success"})
        else:
            return json({"Status": "Error"})

**Comment by lixxu** [comment]
`cur.objects` is a list of `Company` objects (`json` can not recognize them), you can pass `as_raw=True` to `find` to return a list of pymongo documents. 
e.g. `cur = await Company.find(filter=query, as_raw=True)`
please try it.

**Comment by pwalimbe** [comment]
Thanks for the prompt response. It did work although I had to use bson.json_util to serialize object id.
here is the code that worked:
    return json(json_util.dumps(
        {"Status": "Success", "companies": cur.objects}
    ))
